"""Add a column

Revision ID: 0755f40b2238
Revises: 2dad50f4d5a2
Create Date: 2023-03-22 06:57:43.628529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0755f40b2238'
down_revision = '2dad50f4d5a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sequence_ibfk_2', 'sequence', type_='foreignkey')
    op.drop_column('sequence', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence', sa.Column('users_id', mysql.VARCHAR(length=40), nullable=True))
    op.create_foreign_key('sequence_ibfk_2', 'sequence', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
