"""adjust relation table

Revision ID: 26ddb3c278f3
Revises: 3e01983e24a5
Create Date: 2023-03-22 11:55:15.172907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ddb3c278f3'
down_revision = '3e01983e24a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
