"""Add a column

Revision ID: 2dad50f4d5a2
Revises: d1da65e1b8e7
Create Date: 2023-03-22 06:42:51.971830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dad50f4d5a2'
down_revision = 'd1da65e1b8e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
