"""adjust relation table

Revision ID: 3e01983e24a5
Revises: 0755f40b2238
Create Date: 2023-03-22 11:50:29.782336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e01983e24a5'
down_revision = '0755f40b2238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
