"""adjust relation table

Revision ID: 5b1635f1da35
Revises: 26ddb3c278f3
Create Date: 2023-03-22 12:24:43.725939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1635f1da35'
down_revision = '26ddb3c278f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
