"""adjust relation table

Revision ID: 7fc8c2efc14b
Revises: 5b1635f1da35
Create Date: 2023-03-22 12:36:33.720996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc8c2efc14b'
down_revision = '5b1635f1da35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence', sa.Column('call_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence', 'call_status')
    # ### end Alembic commands ###
