"""add new table

Revision ID: 9064e4cbe2a1
Revises: 
Create Date: 2023-03-24 09:11:14.164072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9064e4cbe2a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('blood_type', sa.String(length=225), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('sequence')
    # ### end Alembic commands ###
