"""Add a column

Revision ID: d1da65e1b8e7
Revises: 
Create Date: 2023-03-21 21:10:44.597851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1da65e1b8e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('blood_type', sa.String(length=225), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('group_sequence_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.String(length=40), nullable=True),
    sa.Column('created', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_sequence_id'], ['group_sequence.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('group_sequence')
    # ### end Alembic commands ###
